package bbva.pe.gpr.bean;

import java.math.BigDecimal;

public class Funcion {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_FUNCIONES.COD_FUNCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */ 
    private BigDecimal codFuncion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_FUNCIONES.NOMBRE
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    private String nombre;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_FUNCIONES.DESCRIPCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    private String descripcion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_FUNCIONES.ESTADO
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    private String estado;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_FUNCIONES.COD_FUNCION
     *
     * @return the value of CARDEL.TGPR_FUNCIONES.COD_FUNCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public BigDecimal getCodFuncion() {
        return codFuncion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_FUNCIONES.COD_FUNCION
     *
     * @param codFuncion the value for CARDEL.TGPR_FUNCIONES.COD_FUNCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void setCodFuncion(BigDecimal codFuncion) {
        this.codFuncion = codFuncion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_FUNCIONES.NOMBRE
     *
     * @return the value of CARDEL.TGPR_FUNCIONES.NOMBRE
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_FUNCIONES.NOMBRE
     *
     * @param nombre the value for CARDEL.TGPR_FUNCIONES.NOMBRE
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_FUNCIONES.DESCRIPCION
     *
     * @return the value of CARDEL.TGPR_FUNCIONES.DESCRIPCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_FUNCIONES.DESCRIPCION
     *
     * @param descripcion the value for CARDEL.TGPR_FUNCIONES.DESCRIPCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_FUNCIONES.ESTADO
     *
     * @return the value of CARDEL.TGPR_FUNCIONES.ESTADO
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_FUNCIONES.ESTADO
     *
     * @param estado the value for CARDEL.TGPR_FUNCIONES.ESTADO
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }
}