package bbva.pe.gpr.bean;

import java.math.BigDecimal;

public class FuncionRolKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_FUNCION_ROLES.COD_FUNCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    private BigDecimal codFuncion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_FUNCION_ROLES.COD_ROL
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    private BigDecimal codRol;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_FUNCION_ROLES.COD_FUNCION
     *
     * @return the value of CARDEL.TGPR_FUNCION_ROLES.COD_FUNCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public BigDecimal getCodFuncion() {
        return codFuncion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_FUNCION_ROLES.COD_FUNCION
     *
     * @param codFuncion the value for CARDEL.TGPR_FUNCION_ROLES.COD_FUNCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void setCodFuncion(BigDecimal codFuncion) {
        this.codFuncion = codFuncion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_FUNCION_ROLES.COD_ROL
     *
     * @return the value of CARDEL.TGPR_FUNCION_ROLES.COD_ROL
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public BigDecimal getCodRol() {
        return codRol;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_FUNCION_ROLES.COD_ROL
     *
     * @param codRol the value for CARDEL.TGPR_FUNCION_ROLES.COD_ROL
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void setCodRol(BigDecimal codRol) {
        this.codRol = codRol;
    }
}