package bbva.pe.gpr.bean;

import java.math.BigDecimal;

public class GarantiaDetalleKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DELGPR.TGPR_GARANTIA_DETALLES.COD_GARANTIA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private BigDecimal codGarantia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DELGPR.TGPR_GARANTIA_DETALLES.COD_GARANTIA_DET
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private BigDecimal codGarantiaDet;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DELGPR.TGPR_GARANTIA_DETALLES.COD_GARANTIA
     *
     * @return the value of DELGPR.TGPR_GARANTIA_DETALLES.COD_GARANTIA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public BigDecimal getCodGarantia() {
        return codGarantia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DELGPR.TGPR_GARANTIA_DETALLES.COD_GARANTIA
     *
     * @param codGarantia the value for DELGPR.TGPR_GARANTIA_DETALLES.COD_GARANTIA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setCodGarantia(BigDecimal codGarantia) {
        this.codGarantia = codGarantia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DELGPR.TGPR_GARANTIA_DETALLES.COD_GARANTIA_DET
     *
     * @return the value of DELGPR.TGPR_GARANTIA_DETALLES.COD_GARANTIA_DET
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public BigDecimal getCodGarantiaDet() {
        return codGarantiaDet;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DELGPR.TGPR_GARANTIA_DETALLES.COD_GARANTIA_DET
     *
     * @param codGarantiaDet the value for DELGPR.TGPR_GARANTIA_DETALLES.COD_GARANTIA_DET
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setCodGarantiaDet(BigDecimal codGarantiaDet) {
        this.codGarantiaDet = codGarantiaDet;
    }
}