package bbva.pe.gpr.bean;

import java.math.BigDecimal;

public class Menu {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_MENUS.COD_MENU
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    private BigDecimal codMenu;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_MENUS.DESCRIPCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    private String descripcion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_MENUS.LINK
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    private String link;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_MENUS.POSICION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    private BigDecimal posicion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_MENUS.ESTADO
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    private BigDecimal estado;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_MENUS.COD_MENU
     *
     * @return the value of CARDEL.TGPR_MENUS.COD_MENU
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public BigDecimal getCodMenu() {
        return codMenu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_MENUS.COD_MENU
     *
     * @param codMenu the value for CARDEL.TGPR_MENUS.COD_MENU
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void setCodMenu(BigDecimal codMenu) {
        this.codMenu = codMenu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_MENUS.DESCRIPCION
     *
     * @return the value of CARDEL.TGPR_MENUS.DESCRIPCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_MENUS.DESCRIPCION
     *
     * @param descripcion the value for CARDEL.TGPR_MENUS.DESCRIPCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_MENUS.LINK
     *
     * @return the value of CARDEL.TGPR_MENUS.LINK
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_MENUS.LINK
     *
     * @param link the value for CARDEL.TGPR_MENUS.LINK
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_MENUS.POSICION
     *
     * @return the value of CARDEL.TGPR_MENUS.POSICION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public BigDecimal getPosicion() {
        return posicion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_MENUS.POSICION
     *
     * @param posicion the value for CARDEL.TGPR_MENUS.POSICION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void setPosicion(BigDecimal posicion) {
        this.posicion = posicion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_MENUS.ESTADO
     *
     * @return the value of CARDEL.TGPR_MENUS.ESTADO
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public BigDecimal getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_MENUS.ESTADO
     *
     * @param estado the value for CARDEL.TGPR_MENUS.ESTADO
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void setEstado(BigDecimal estado) {
        this.estado = estado;
    }
}