package bbva.pe.gpr.bean;

public class MultitablaDetalleKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DELGPR.TGPR_MULTITABLA_DETALLE.COD_ELEMENTO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private String codElemento;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DELGPR.TGPR_MULTITABLA_DETALLE.COD_MULTITABLA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private String codMultitabla;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DELGPR.TGPR_MULTITABLA_DETALLE.COD_ELEMENTO
     *
     * @return the value of DELGPR.TGPR_MULTITABLA_DETALLE.COD_ELEMENTO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public String getCodElemento() {
        return codElemento;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DELGPR.TGPR_MULTITABLA_DETALLE.COD_ELEMENTO
     *
     * @param codElemento the value for DELGPR.TGPR_MULTITABLA_DETALLE.COD_ELEMENTO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setCodElemento(String codElemento) {
        this.codElemento = codElemento == null ? null : codElemento.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DELGPR.TGPR_MULTITABLA_DETALLE.COD_MULTITABLA
     *
     * @return the value of DELGPR.TGPR_MULTITABLA_DETALLE.COD_MULTITABLA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public String getCodMultitabla() {
        return codMultitabla;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DELGPR.TGPR_MULTITABLA_DETALLE.COD_MULTITABLA
     *
     * @param codMultitabla the value for DELGPR.TGPR_MULTITABLA_DETALLE.COD_MULTITABLA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setCodMultitabla(String codMultitabla) {
        this.codMultitabla = codMultitabla == null ? null : codMultitabla.trim();
    }
}