package bbva.pe.gpr.bean;

import java.math.BigDecimal;
import java.util.Date;

public class Producto {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_PRODUCTOS.COD_PRODUCTO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private BigDecimal codProducto;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_PRODUCTOS.DESCRIPCION
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private String descripcion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_PRODUCTOS.COD_BANCA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private BigDecimal codBanca;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_PRODUCTOS.COD_PRODUCTO_BASE
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private BigDecimal codProductoBase;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_PRODUCTOS.FECHA_CREACION
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private Date fechaCreacion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_PRODUCTOS.VIGENCIA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private Date vigencia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_PRODUCTOS.ESTADO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private BigDecimal estado;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_PRODUCTOS.COD_PRODUCTO
     *
     * @return the value of CARDEL.TGPR_PRODUCTOS.COD_PRODUCTO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public BigDecimal getCodProducto() {
        return codProducto;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_PRODUCTOS.COD_PRODUCTO
     *
     * @param codProducto the value for CARDEL.TGPR_PRODUCTOS.COD_PRODUCTO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setCodProducto(BigDecimal codProducto) {
        this.codProducto = codProducto;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_PRODUCTOS.DESCRIPCION
     *
     * @return the value of CARDEL.TGPR_PRODUCTOS.DESCRIPCION
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_PRODUCTOS.DESCRIPCION
     *
     * @param descripcion the value for CARDEL.TGPR_PRODUCTOS.DESCRIPCION
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_PRODUCTOS.COD_BANCA
     *
     * @return the value of CARDEL.TGPR_PRODUCTOS.COD_BANCA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public BigDecimal getCodBanca() {
        return codBanca;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_PRODUCTOS.COD_BANCA
     *
     * @param codBanca the value for CARDEL.TGPR_PRODUCTOS.COD_BANCA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setCodBanca(BigDecimal codBanca) {
        this.codBanca = codBanca;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_PRODUCTOS.COD_PRODUCTO_BASE
     *
     * @return the value of CARDEL.TGPR_PRODUCTOS.COD_PRODUCTO_BASE
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public BigDecimal getCodProductoBase() {
        return codProductoBase;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_PRODUCTOS.COD_PRODUCTO_BASE
     *
     * @param codProductoBase the value for CARDEL.TGPR_PRODUCTOS.COD_PRODUCTO_BASE
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setCodProductoBase(BigDecimal codProductoBase) {
        this.codProductoBase = codProductoBase;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_PRODUCTOS.FECHA_CREACION
     *
     * @return the value of CARDEL.TGPR_PRODUCTOS.FECHA_CREACION
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_PRODUCTOS.FECHA_CREACION
     *
     * @param fechaCreacion the value for CARDEL.TGPR_PRODUCTOS.FECHA_CREACION
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_PRODUCTOS.VIGENCIA
     *
     * @return the value of CARDEL.TGPR_PRODUCTOS.VIGENCIA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public Date getVigencia() {
        return vigencia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_PRODUCTOS.VIGENCIA
     *
     * @param vigencia the value for CARDEL.TGPR_PRODUCTOS.VIGENCIA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setVigencia(Date vigencia) {
        this.vigencia = vigencia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_PRODUCTOS.ESTADO
     *
     * @return the value of CARDEL.TGPR_PRODUCTOS.ESTADO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public BigDecimal getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_PRODUCTOS.ESTADO
     *
     * @param estado the value for CARDEL.TGPR_PRODUCTOS.ESTADO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setEstado(BigDecimal estado) {
        this.estado = estado;
    }
}