package bbva.pe.gpr.bean;

import java.math.BigDecimal;

public class Territorio {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_TERRITORIOS.COD_TERRITORIO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private BigDecimal codTerritorio;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_TERRITORIOS.NOMBRE
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private BigDecimal nombre;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_TERRITORIOS.ESTADO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private BigDecimal estado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_TERRITORIOS.DETALLE
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private String detalle;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_TERRITORIOS.COD_TERRITORIO
     *
     * @return the value of CARDEL.TGPR_TERRITORIOS.COD_TERRITORIO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public BigDecimal getCodTerritorio() {
        return codTerritorio;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_TERRITORIOS.COD_TERRITORIO
     *
     * @param codTerritorio the value for CARDEL.TGPR_TERRITORIOS.COD_TERRITORIO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setCodTerritorio(BigDecimal codTerritorio) {
        this.codTerritorio = codTerritorio;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_TERRITORIOS.NOMBRE
     *
     * @return the value of CARDEL.TGPR_TERRITORIOS.NOMBRE
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public BigDecimal getNombre() {
        return nombre;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_TERRITORIOS.NOMBRE
     *
     * @param nombre the value for CARDEL.TGPR_TERRITORIOS.NOMBRE
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setNombre(BigDecimal nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_TERRITORIOS.ESTADO
     *
     * @return the value of CARDEL.TGPR_TERRITORIOS.ESTADO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public BigDecimal getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_TERRITORIOS.ESTADO
     *
     * @param estado the value for CARDEL.TGPR_TERRITORIOS.ESTADO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setEstado(BigDecimal estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_TERRITORIOS.DETALLE
     *
     * @return the value of CARDEL.TGPR_TERRITORIOS.DETALLE
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public String getDetalle() {
        return detalle;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_TERRITORIOS.DETALLE
     *
     * @param detalle the value for CARDEL.TGPR_TERRITORIOS.DETALLE
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setDetalle(String detalle) {
        this.detalle = detalle == null ? null : detalle.trim();
    }
}