package bbva.pe.gpr.bean;

import java.math.BigDecimal;

public class UsuarioSubanca extends UsuarioSubancaKey {
	private BigDecimal codBanca;
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DELGPR.TGPR_USUARIO_SUBANCAS.ESTADO
     *
     * @ibatorgenerated Wed Oct 10 16:31:18 COT 2012
     */
    private BigDecimal estado;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DELGPR.TGPR_USUARIO_SUBANCAS.ESTADO
     *
     * @return the value of DELGPR.TGPR_USUARIO_SUBANCAS.ESTADO
     *
     * @ibatorgenerated Wed Oct 10 16:31:18 COT 2012
     */
    public BigDecimal getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DELGPR.TGPR_USUARIO_SUBANCAS.ESTADO
     *
     * @param estado the value for DELGPR.TGPR_USUARIO_SUBANCAS.ESTADO
     *
     * @ibatorgenerated Wed Oct 10 16:31:18 COT 2012
     */
    public void setEstado(BigDecimal estado) {
        this.estado = estado;
    }

	public BigDecimal getCodBanca() {
		return codBanca;
	}

	public void setCodBanca(BigDecimal codBanca) {
		this.codBanca = codBanca;
	}
    
    
}