package bbva.pe.gpr.bean;

import java.math.BigDecimal;

public class UsuarioRolKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DELGPR.TGPR_USUARIO_ROLES.COD_ROL
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    private BigDecimal codRol;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DELGPR.TGPR_USUARIO_ROLES.COD_USUARIO
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    private String codUsuario;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DELGPR.TGPR_USUARIO_ROLES.COD_ROL
     *
     * @return the value of DELGPR.TGPR_USUARIO_ROLES.COD_ROL
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public BigDecimal getCodRol() {
        return codRol;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DELGPR.TGPR_USUARIO_ROLES.COD_ROL
     *
     * @param codRol the value for DELGPR.TGPR_USUARIO_ROLES.COD_ROL
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public void setCodRol(BigDecimal codRol) {
        this.codRol = codRol;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DELGPR.TGPR_USUARIO_ROLES.COD_USUARIO
     *
     * @return the value of DELGPR.TGPR_USUARIO_ROLES.COD_USUARIO
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public String getCodUsuario() {
        return codUsuario;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DELGPR.TGPR_USUARIO_ROLES.COD_USUARIO
     *
     * @param codUsuario the value for DELGPR.TGPR_USUARIO_ROLES.COD_USUARIO
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public void setCodUsuario(String codUsuario) {
        this.codUsuario = codUsuario == null ? null : codUsuario.trim();
    }
}