package bbva.pe.gpr.bean;

import java.math.BigDecimal;

public class FuncionRol extends FuncionRolKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_FUNCION_ROLES.POSICION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    private BigDecimal posicion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_FUNCION_ROLES.ESTADO
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    private BigDecimal estado;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_FUNCION_ROLES.POSICION
     *
     * @return the value of CARDEL.TGPR_FUNCION_ROLES.POSICION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public BigDecimal getPosicion() {
        return posicion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_FUNCION_ROLES.POSICION
     *
     * @param posicion the value for CARDEL.TGPR_FUNCION_ROLES.POSICION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void setPosicion(BigDecimal posicion) {
        this.posicion = posicion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_FUNCION_ROLES.ESTADO
     *
     * @return the value of CARDEL.TGPR_FUNCION_ROLES.ESTADO
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public BigDecimal getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_FUNCION_ROLES.ESTADO
     *
     * @param estado the value for CARDEL.TGPR_FUNCION_ROLES.ESTADO
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void setEstado(BigDecimal estado) {
        this.estado = estado;
    }
}