package bbva.pe.gpr.bean;

import java.math.BigDecimal;

public class Garantia {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_GARANTIAS.COD_GARANTIA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private BigDecimal codGarantia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_GARANTIAS.NOMBRE
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private String nombre;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_GARANTIAS.ESTADO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private BigDecimal estado;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_GARANTIAS.COD_GARANTIA
     *
     * @return the value of CARDEL.TGPR_GARANTIAS.COD_GARANTIA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public BigDecimal getCodGarantia() {
        return codGarantia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_GARANTIAS.COD_GARANTIA
     *
     * @param codGarantia the value for CARDEL.TGPR_GARANTIAS.COD_GARANTIA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setCodGarantia(BigDecimal codGarantia) {
        this.codGarantia = codGarantia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_GARANTIAS.NOMBRE
     *
     * @return the value of CARDEL.TGPR_GARANTIAS.NOMBRE
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_GARANTIAS.NOMBRE
     *
     * @param nombre the value for CARDEL.TGPR_GARANTIAS.NOMBRE
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_GARANTIAS.ESTADO
     *
     * @return the value of CARDEL.TGPR_GARANTIAS.ESTADO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public BigDecimal getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_GARANTIAS.ESTADO
     *
     * @param estado the value for CARDEL.TGPR_GARANTIAS.ESTADO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setEstado(BigDecimal estado) {
        this.estado = estado;
    }
}