package bbva.pe.gpr.bean;

import java.math.BigDecimal;

public class GarantiaDetalle extends GarantiaDetalleKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_GARANTIA_DETALLES.ESTADO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private String estado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_GARANTIA_DETALLES.COD_CONFIGURACION
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private BigDecimal codConfiguracion;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_GARANTIA_DETALLES.ESTADO
     *
     * @return the value of CARDEL.TGPR_GARANTIA_DETALLES.ESTADO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_GARANTIA_DETALLES.ESTADO
     *
     * @param estado the value for CARDEL.TGPR_GARANTIA_DETALLES.ESTADO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_GARANTIA_DETALLES.COD_CONFIGURACION
     *
     * @return the value of CARDEL.TGPR_GARANTIA_DETALLES.COD_CONFIGURACION
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public BigDecimal getCodConfiguracion() {
        return codConfiguracion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_GARANTIA_DETALLES.COD_CONFIGURACION
     *
     * @param codConfiguracion the value for CARDEL.TGPR_GARANTIA_DETALLES.COD_CONFIGURACION
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setCodConfiguracion(BigDecimal codConfiguracion) {
        this.codConfiguracion = codConfiguracion;
    }
}