package bbva.pe.gpr.bean;

import java.math.BigDecimal;
import java.util.Date;

public class Log {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DELGPR.TGPR_LOGS.COD_LOG
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    private BigDecimal codLog;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DELGPR.TGPR_LOGS.COD_MULT_TRANSACCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    private String codMultTransaccion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DELGPR.TGPR_LOGS.DES_TRANSACCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    private String desTransaccion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DELGPR.TGPR_LOGS.DESCRIPCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    private String descripcion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DELGPR.TGPR_LOGS.FECHA_HORA
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    private Date fechaHora;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DELGPR.TGPR_LOGS.USUARIO
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    private String usuario;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DELGPR.TGPR_LOGS.ESTADO
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    private BigDecimal estado;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DELGPR.TGPR_LOGS.COD_LOG
     *
     * @return the value of DELGPR.TGPR_LOGS.COD_LOG
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public BigDecimal getCodLog() {
        return codLog;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DELGPR.TGPR_LOGS.COD_LOG
     *
     * @param codLog the value for DELGPR.TGPR_LOGS.COD_LOG
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void setCodLog(BigDecimal codLog) {
        this.codLog = codLog;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DELGPR.TGPR_LOGS.COD_MULT_TRANSACCION
     *
     * @return the value of DELGPR.TGPR_LOGS.COD_MULT_TRANSACCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public String getCodMultTransaccion() {
        return codMultTransaccion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DELGPR.TGPR_LOGS.COD_MULT_TRANSACCION
     *
     * @param codMultTransaccion the value for DELGPR.TGPR_LOGS.COD_MULT_TRANSACCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void setCodMultTransaccion(String codMultTransaccion) {
        this.codMultTransaccion = codMultTransaccion == null ? null : codMultTransaccion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DELGPR.TGPR_LOGS.DES_TRANSACCION
     *
     * @return the value of DELGPR.TGPR_LOGS.DES_TRANSACCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public String getDesTransaccion() {
        return desTransaccion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DELGPR.TGPR_LOGS.DES_TRANSACCION
     *
     * @param desTransaccion the value for DELGPR.TGPR_LOGS.DES_TRANSACCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void setDesTransaccion(String desTransaccion) {
        this.desTransaccion = desTransaccion == null ? null : desTransaccion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DELGPR.TGPR_LOGS.DESCRIPCION
     *
     * @return the value of DELGPR.TGPR_LOGS.DESCRIPCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DELGPR.TGPR_LOGS.DESCRIPCION
     *
     * @param descripcion the value for DELGPR.TGPR_LOGS.DESCRIPCION
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DELGPR.TGPR_LOGS.FECHA_HORA
     *
     * @return the value of DELGPR.TGPR_LOGS.FECHA_HORA
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public Date getFechaHora() {
        return fechaHora;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DELGPR.TGPR_LOGS.FECHA_HORA
     *
     * @param fechaHora the value for DELGPR.TGPR_LOGS.FECHA_HORA
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DELGPR.TGPR_LOGS.USUARIO
     *
     * @return the value of DELGPR.TGPR_LOGS.USUARIO
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public String getUsuario() {
        return usuario;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DELGPR.TGPR_LOGS.USUARIO
     *
     * @param usuario the value for DELGPR.TGPR_LOGS.USUARIO
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void setUsuario(String usuario) {
        this.usuario = usuario == null ? null : usuario.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DELGPR.TGPR_LOGS.ESTADO
     *
     * @return the value of DELGPR.TGPR_LOGS.ESTADO
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public BigDecimal getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DELGPR.TGPR_LOGS.ESTADO
     *
     * @param estado the value for DELGPR.TGPR_LOGS.ESTADO
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void setEstado(BigDecimal estado) {
        this.estado = estado;
    }
}