package bbva.pe.gpr.bean;

import java.math.BigDecimal;

public class Multitabla {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_MULTITABLA.COD_MULTITABLA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private String codMultitabla;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_MULTITABLA.NOMBRE
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private String nombre;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_MULTITABLA.DESCRRIPCION
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private String descrripcion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_MULTITABLA.CORRELATIVO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private BigDecimal correlativo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_MULTITABLA.ESTADO_TABLA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private String estadoTabla;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_MULTITABLA.ESTADO_REGISTRO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private BigDecimal estadoRegistro;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_MULTITABLA.COD_MULTITABLA
     *
     * @return the value of CARDEL.TGPR_MULTITABLA.COD_MULTITABLA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public String getCodMultitabla() {
        return codMultitabla;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_MULTITABLA.COD_MULTITABLA
     *
     * @param codMultitabla the value for CARDEL.TGPR_MULTITABLA.COD_MULTITABLA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setCodMultitabla(String codMultitabla) {
        this.codMultitabla = codMultitabla == null ? null : codMultitabla.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_MULTITABLA.NOMBRE
     *
     * @return the value of CARDEL.TGPR_MULTITABLA.NOMBRE
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_MULTITABLA.NOMBRE
     *
     * @param nombre the value for CARDEL.TGPR_MULTITABLA.NOMBRE
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_MULTITABLA.DESCRRIPCION
     *
     * @return the value of CARDEL.TGPR_MULTITABLA.DESCRRIPCION
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public String getDescrripcion() {
        return descrripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_MULTITABLA.DESCRRIPCION
     *
     * @param descrripcion the value for CARDEL.TGPR_MULTITABLA.DESCRRIPCION
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setDescrripcion(String descrripcion) {
        this.descrripcion = descrripcion == null ? null : descrripcion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_MULTITABLA.CORRELATIVO
     *
     * @return the value of CARDEL.TGPR_MULTITABLA.CORRELATIVO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public BigDecimal getCorrelativo() {
        return correlativo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_MULTITABLA.CORRELATIVO
     *
     * @param correlativo the value for CARDEL.TGPR_MULTITABLA.CORRELATIVO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setCorrelativo(BigDecimal correlativo) {
        this.correlativo = correlativo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_MULTITABLA.ESTADO_TABLA
     *
     * @return the value of CARDEL.TGPR_MULTITABLA.ESTADO_TABLA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public String getEstadoTabla() {
        return estadoTabla;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_MULTITABLA.ESTADO_TABLA
     *
     * @param estadoTabla the value for CARDEL.TGPR_MULTITABLA.ESTADO_TABLA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setEstadoTabla(String estadoTabla) {
        this.estadoTabla = estadoTabla == null ? null : estadoTabla.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_MULTITABLA.ESTADO_REGISTRO
     *
     * @return the value of CARDEL.TGPR_MULTITABLA.ESTADO_REGISTRO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public BigDecimal getEstadoRegistro() {
        return estadoRegistro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_MULTITABLA.ESTADO_REGISTRO
     *
     * @param estadoRegistro the value for CARDEL.TGPR_MULTITABLA.ESTADO_REGISTRO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setEstadoRegistro(BigDecimal estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
}