package bbva.pe.gpr.bean;

import java.math.BigDecimal;

public class ProductoGarantiaKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_PRODUCTO_GARANTIAS.COD_GARANTIA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private BigDecimal codGarantia;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_PRODUCTO_GARANTIAS.COD_PROD_GARANTIA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private BigDecimal codProdGarantia;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_PRODUCTO_GARANTIAS.COD_GARANTIA
     *
     * @return the value of CARDEL.TGPR_PRODUCTO_GARANTIAS.COD_GARANTIA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public BigDecimal getCodGarantia() {
        return codGarantia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_PRODUCTO_GARANTIAS.COD_GARANTIA
     *
     * @param codGarantia the value for CARDEL.TGPR_PRODUCTO_GARANTIAS.COD_GARANTIA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setCodGarantia(BigDecimal codGarantia) {
        this.codGarantia = codGarantia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_PRODUCTO_GARANTIAS.COD_PROD_GARANTIA
     *
     * @return the value of CARDEL.TGPR_PRODUCTO_GARANTIAS.COD_PROD_GARANTIA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public BigDecimal getCodProdGarantia() {
        return codProdGarantia;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_PRODUCTO_GARANTIAS.COD_PROD_GARANTIA
     *
     * @param codProdGarantia the value for CARDEL.TGPR_PRODUCTO_GARANTIAS.COD_PROD_GARANTIA
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setCodProdGarantia(BigDecimal codProdGarantia) {
        this.codProdGarantia = codProdGarantia;
    }
}