package bbva.pe.gpr.bean;

import java.math.BigDecimal;

public class ProductoGarantia extends ProductoGarantiaKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_PRODUCTO_GARANTIAS.ESTADO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private BigDecimal estado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_PRODUCTO_GARANTIAS.COD_PRODUCTO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    private BigDecimal codProducto;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_PRODUCTO_GARANTIAS.ESTADO
     *
     * @return the value of CARDEL.TGPR_PRODUCTO_GARANTIAS.ESTADO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public BigDecimal getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_PRODUCTO_GARANTIAS.ESTADO
     *
     * @param estado the value for CARDEL.TGPR_PRODUCTO_GARANTIAS.ESTADO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setEstado(BigDecimal estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_PRODUCTO_GARANTIAS.COD_PRODUCTO
     *
     * @return the value of CARDEL.TGPR_PRODUCTO_GARANTIAS.COD_PRODUCTO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public BigDecimal getCodProducto() {
        return codProducto;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_PRODUCTO_GARANTIAS.COD_PRODUCTO
     *
     * @param codProducto the value for CARDEL.TGPR_PRODUCTO_GARANTIAS.COD_PRODUCTO
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void setCodProducto(BigDecimal codProducto) {
        this.codProducto = codProducto;
    }
}