package bbva.pe.gpr.bean;

import java.math.BigDecimal;

public class UsuarioRol extends UsuarioRolKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DELGPR.TGPR_USUARIO_ROLES.DESCRIPCION
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    private String descripcion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DELGPR.TGPR_USUARIO_ROLES.ESTADO
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    private BigDecimal estado;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DELGPR.TGPR_USUARIO_ROLES.DESCRIPCION
     *
     * @return the value of DELGPR.TGPR_USUARIO_ROLES.DESCRIPCION
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DELGPR.TGPR_USUARIO_ROLES.DESCRIPCION
     *
     * @param descripcion the value for DELGPR.TGPR_USUARIO_ROLES.DESCRIPCION
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DELGPR.TGPR_USUARIO_ROLES.ESTADO
     *
     * @return the value of DELGPR.TGPR_USUARIO_ROLES.ESTADO
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public BigDecimal getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DELGPR.TGPR_USUARIO_ROLES.ESTADO
     *
     * @param estado the value for DELGPR.TGPR_USUARIO_ROLES.ESTADO
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public void setEstado(BigDecimal estado) {
        this.estado = estado;
    }
}