package bbva.pe.gpr.bean;

public class UsuarioSubancaKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_USUARIO_SUBANCAS.COD_SUBANCA
     *
     * @ibatorgenerated Wed Oct 10 16:31:18 COT 2012
     */
    private String codSubanca;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CARDEL.TGPR_USUARIO_SUBANCAS.COD_USUARIO
     *
     * @ibatorgenerated Wed Oct 10 16:31:18 COT 2012
     */
    private String codUsuario;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_USUARIO_SUBANCAS.COD_SUBANCA
     *
     * @return the value of CARDEL.TGPR_USUARIO_SUBANCAS.COD_SUBANCA
     *
     * @ibatorgenerated Wed Oct 10 16:31:18 COT 2012
     */
    public String getCodSubanca() {
        return codSubanca;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_USUARIO_SUBANCAS.COD_SUBANCA
     *
     * @param codSubanca the value for CARDEL.TGPR_USUARIO_SUBANCAS.COD_SUBANCA
     *
     * @ibatorgenerated Wed Oct 10 16:31:18 COT 2012
     */
    public void setCodSubanca(String codSubanca) {
        this.codSubanca = codSubanca == null ? null : codSubanca.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CARDEL.TGPR_USUARIO_SUBANCAS.COD_USUARIO
     *
     * @return the value of CARDEL.TGPR_USUARIO_SUBANCAS.COD_USUARIO
     *
     * @ibatorgenerated Wed Oct 10 16:31:18 COT 2012
     */
    public String getCodUsuario() {
        return codUsuario;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CARDEL.TGPR_USUARIO_SUBANCAS.COD_USUARIO
     *
     * @param codUsuario the value for CARDEL.TGPR_USUARIO_SUBANCAS.COD_USUARIO
     *
     * @ibatorgenerated Wed Oct 10 16:31:18 COT 2012
     */
    public void setCodUsuario(String codUsuario) {
        this.codUsuario = codUsuario == null ? null : codUsuario.trim();
    }
}