package bbva.pe.gpr.dao;

import bbva.pe.gpr.bean.Garantia;
import java.math.BigDecimal;

public interface GarantiaDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_GARANTIAS
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    int deleteByPrimaryKey(BigDecimal codGarantia);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_GARANTIAS
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    void insert(Garantia record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_GARANTIAS
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    void insertSelective(Garantia record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_GARANTIAS
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    Garantia selectByPrimaryKey(BigDecimal codGarantia);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_GARANTIAS
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    int updateByPrimaryKeySelective(Garantia record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_GARANTIAS
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    int updateByPrimaryKey(Garantia record);
}