package bbva.pe.gpr.dao;

import bbva.pe.gpr.bean.SolicitudMensaje;
import java.math.BigDecimal;

public interface SolicitudMensajeDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_SOLICITUD_MENSAJES
     *
     * @ibatorgenerated Tue Sep 25 16:58:42 COT 2012
     */
    int deleteByPrimaryKey(BigDecimal codMensaje);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_SOLICITUD_MENSAJES
     *
     * @ibatorgenerated Tue Sep 25 16:58:42 COT 2012
     */
    void insert(SolicitudMensaje record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_SOLICITUD_MENSAJES
     *
     * @ibatorgenerated Tue Sep 25 16:58:42 COT 2012
     */
    void insertSelective(SolicitudMensaje record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_SOLICITUD_MENSAJES
     *
     * @ibatorgenerated Tue Sep 25 16:58:42 COT 2012
     */
    SolicitudMensaje selectByPrimaryKey(BigDecimal codMensaje);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_SOLICITUD_MENSAJES
     *
     * @ibatorgenerated Tue Sep 25 16:58:42 COT 2012
     */
    int updateByPrimaryKeySelective(SolicitudMensaje record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_SOLICITUD_MENSAJES
     *
     * @ibatorgenerated Tue Sep 25 16:58:42 COT 2012
     */
    int updateByPrimaryKey(SolicitudMensaje record);
}