package bbva.pe.gpr.service;

import bbva.pe.gpr.bean.SolicitudOperacion;

public interface SolicitudOperacionService {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_SOLICITUD_OPERACIONES
     *
     * @ibatorgenerated Mon Sep 24 11:24:02 COT 2012
     */
    void insert(SolicitudOperacion record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_SOLICITUD_OPERACIONES
     *
     * @ibatorgenerated Mon Sep 24 11:24:02 COT 2012
     */
    void insertSelective(SolicitudOperacion record);
}