package bbva.pe.gpr.daoImpl;



import bbva.pe.gpr.bean.BancaSub;
import bbva.pe.gpr.dao.BancaSubDAO;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class BancaSubDAOImpl extends SqlMapClientDaoSupport implements BancaSubDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_BANCA_SUB
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public BancaSubDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_BANCA_SUB
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public int deleteByPrimaryKey(String codSubbanca) {
        BancaSub key = new BancaSub();
        key.setCodSubanca(codSubbanca);
        int rows = getSqlMapClientTemplate().delete("DELGPR_TGPR_BANCA_SUB.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_BANCA_SUB
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public void insert(BancaSub record) {
        getSqlMapClientTemplate().insert("DELGPR_TGPR_BANCA_SUB.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_BANCA_SUB
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public void insertSelective(BancaSub record) {
        getSqlMapClientTemplate().insert("DELGPR_TGPR_BANCA_SUB.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_BANCA_SUB
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public BancaSub selectByPrimaryKey(String codSubbanca) {
        BancaSub key = new BancaSub();
        key.setCodSubanca(codSubbanca);
        BancaSub record = (BancaSub) getSqlMapClientTemplate().queryForObject("DELGPR_TGPR_BANCA_SUB.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_BANCA_SUB
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public int updateByPrimaryKeySelective(BancaSub record) {
        int rows = getSqlMapClientTemplate().update("DELGPR_TGPR_BANCA_SUB.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_BANCA_SUB
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public int updateByPrimaryKey(BancaSub record) {
        int rows = getSqlMapClientTemplate().update("DELGPR_TGPR_BANCA_SUB.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}