package bbva.pe.gpr.daoImpl;

import bbva.pe.gpr.bean.Log;
import bbva.pe.gpr.dao.LogDAO;

import java.math.BigDecimal;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class LogDAOImpl extends SqlMapClientDaoSupport implements LogDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_LOGS
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public LogDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_LOGS
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public int deleteByPrimaryKey(BigDecimal codLog) {
        Log key = new Log();
        key.setCodLog(codLog);
        int rows = getSqlMapClientTemplate().delete("DELGPR_TGPR_LOGS.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_LOGS
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void insert(Log record) {
        getSqlMapClientTemplate().insert("DELGPR_TGPR_LOGS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_LOGS
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void insertSelective(Log record) {
        getSqlMapClientTemplate().insert("DELGPR_TGPR_LOGS.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_LOGS
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public Log selectByPrimaryKey(BigDecimal codLog) {
        Log key = new Log();
        key.setCodLog(codLog);
        Log record = (Log) getSqlMapClientTemplate().queryForObject("DELGPR_TGPR_LOGS.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_LOGS
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public int updateByPrimaryKeySelective(Log record) {
        int rows = getSqlMapClientTemplate().update("DELGPR_TGPR_LOGS.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_LOGS
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public int updateByPrimaryKey(Log record) {
        int rows = getSqlMapClientTemplate().update("DELGPR_TGPR_LOGS.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}