package bbva.pe.gpr.daoImpl;

import bbva.pe.gpr.bean.Menu;
import bbva.pe.gpr.dao.MenuDAO;

import java.math.BigDecimal;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MenuDAOImpl extends SqlMapClientDaoSupport implements MenuDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_MENUS
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public MenuDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_MENUS
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public int deleteByPrimaryKey(BigDecimal codMenu) {
        Menu key = new Menu();
        key.setCodMenu(codMenu);
        int rows = getSqlMapClientTemplate().delete("CARDEL_TGPR_MENUS.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_MENUS
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void insert(Menu record) {
        getSqlMapClientTemplate().insert("CARDEL_TGPR_MENUS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_MENUS
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void insertSelective(Menu record) {
        getSqlMapClientTemplate().insert("CARDEL_TGPR_MENUS.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_MENUS
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public Menu selectByPrimaryKey(BigDecimal codMenu) {
        Menu key = new Menu();
        key.setCodMenu(codMenu);
        Menu record = (Menu) getSqlMapClientTemplate().queryForObject("CARDEL_TGPR_MENUS.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_MENUS
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public int updateByPrimaryKeySelective(Menu record) {
        int rows = getSqlMapClientTemplate().update("CARDEL_TGPR_MENUS.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_MENUS
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public int updateByPrimaryKey(Menu record) {
        int rows = getSqlMapClientTemplate().update("CARDEL_TGPR_MENUS.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}