package bbva.pe.gpr.daoImpl;

import bbva.pe.gpr.bean.SolicitudMensaje;
import bbva.pe.gpr.dao.SolicitudMensajeDAO;

import java.math.BigDecimal;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SolicitudMensajeDAOImpl extends SqlMapClientDaoSupport implements SolicitudMensajeDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_SOLICITUD_MENSAJES
     *
     * @ibatorgenerated Tue Sep 25 16:58:42 COT 2012
     */
    public SolicitudMensajeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_SOLICITUD_MENSAJES
     *
     * @ibatorgenerated Tue Sep 25 16:58:42 COT 2012
     */
    public int deleteByPrimaryKey(BigDecimal codMensaje) {
        SolicitudMensaje key = new SolicitudMensaje();
        key.setCodMensaje(codMensaje);
        int rows = getSqlMapClientTemplate().delete("CARDEL_TGPR_SOLICITUD_MENSAJES.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_SOLICITUD_MENSAJES
     *
     * @ibatorgenerated Tue Sep 25 16:58:42 COT 2012
     */
    public void insert(SolicitudMensaje record) {
        getSqlMapClientTemplate().insert("CARDEL_TGPR_SOLICITUD_MENSAJES.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_SOLICITUD_MENSAJES
     *
     * @ibatorgenerated Tue Sep 25 16:58:42 COT 2012
     */
    public void insertSelective(SolicitudMensaje record) {
        getSqlMapClientTemplate().insert("CARDEL_TGPR_SOLICITUD_MENSAJES.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_SOLICITUD_MENSAJES
     *
     * @ibatorgenerated Tue Sep 25 16:58:42 COT 2012
     */
    public SolicitudMensaje selectByPrimaryKey(BigDecimal codMensaje) {
        SolicitudMensaje key = new SolicitudMensaje();
        key.setCodMensaje(codMensaje);
        SolicitudMensaje record = (SolicitudMensaje) getSqlMapClientTemplate().queryForObject("CARDEL_TGPR_SOLICITUD_MENSAJES.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_SOLICITUD_MENSAJES
     *
     * @ibatorgenerated Tue Sep 25 16:58:42 COT 2012
     */
    public int updateByPrimaryKeySelective(SolicitudMensaje record) {
        int rows = getSqlMapClientTemplate().update("CARDEL_TGPR_SOLICITUD_MENSAJES.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_SOLICITUD_MENSAJES
     *
     * @ibatorgenerated Tue Sep 25 16:58:42 COT 2012
     */
    public int updateByPrimaryKey(SolicitudMensaje record) {
        int rows = getSqlMapClientTemplate().update("CARDEL_TGPR_SOLICITUD_MENSAJES.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}