package bbva.pe.gpr.daoImpl;


import bbva.pe.gpr.bean.UsuarioSubanca;
import bbva.pe.gpr.bean.UsuarioSubancaKey;
import bbva.pe.gpr.dao.UsuarioSubancaDAO;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UsuarioSubancaDAOImpl extends SqlMapClientDaoSupport implements UsuarioSubancaDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_USUARIO_SUBANCAS
     *
     * @ibatorgenerated Wed Oct 10 16:31:18 COT 2012
     */
    public UsuarioSubancaDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_USUARIO_SUBANCAS
     *
     * @ibatorgenerated Wed Oct 10 16:31:18 COT 2012
     */
    public int deleteByPrimaryKey(UsuarioSubancaKey key) {
        int rows = getSqlMapClientTemplate().delete("DELGPR_TGPR_USUARIO_SUBANCAS.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_USUARIO_SUBANCAS
     *
     * @ibatorgenerated Wed Oct 10 16:31:18 COT 2012
     */
    public void insert(UsuarioSubanca record) {
        getSqlMapClientTemplate().insert("DELGPR_TGPR_USUARIO_SUBANCAS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_USUARIO_SUBANCAS
     *
     * @ibatorgenerated Wed Oct 10 16:31:18 COT 2012
     */
    public void insertSelective(UsuarioSubanca record) {
        getSqlMapClientTemplate().insert("DELGPR_TGPR_USUARIO_SUBANCAS.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_USUARIO_SUBANCAS
     *
     * @ibatorgenerated Wed Oct 10 16:31:18 COT 2012
     */
    public UsuarioSubanca selectByPrimaryKey(UsuarioSubancaKey key) {
        UsuarioSubanca record = (UsuarioSubanca) getSqlMapClientTemplate().queryForObject("DELGPR_TGPR_USUARIO_SUBANCAS.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_USUARIO_SUBANCAS
     *
     * @ibatorgenerated Wed Oct 10 16:31:18 COT 2012
     */
    public int updateByPrimaryKeySelective(UsuarioSubanca record) {
        int rows = getSqlMapClientTemplate().update("DELGPR_TGPR_USUARIO_SUBANCAS.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_USUARIO_SUBANCAS
     *
     * @ibatorgenerated Wed Oct 10 16:31:18 COT 2012
     */
    public int updateByPrimaryKey(UsuarioSubanca record) {
        int rows = getSqlMapClientTemplate().update("DELGPR_TGPR_USUARIO_SUBANCAS.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}