package bbva.pe.gpr.daoImpl;

import bbva.pe.gpr.bean.MenuRol;
import bbva.pe.gpr.bean.MenuRolKey;
import bbva.pe.gpr.dao.MenuRolDAO;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MenuRolDAOImpl extends SqlMapClientDaoSupport implements MenuRolDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_MENU_ROLES
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public MenuRolDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_MENU_ROLES
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public int deleteByPrimaryKey(MenuRolKey key) {
        int rows = getSqlMapClientTemplate().delete("DELGPR_TGPR_MENU_ROLES.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_MENU_ROLES
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void insert(MenuRol record) {
        getSqlMapClientTemplate().insert("DELGPR_TGPR_MENU_ROLES.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_MENU_ROLES
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public void insertSelective(MenuRol record) {
        getSqlMapClientTemplate().insert("DELGPR_TGPR_MENU_ROLES.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_MENU_ROLES
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public MenuRol selectByPrimaryKey(MenuRolKey key) {
        MenuRol record = (MenuRol) getSqlMapClientTemplate().queryForObject("DELGPR_TGPR_MENU_ROLES.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_MENU_ROLES
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public int updateByPrimaryKeySelective(MenuRol record) {
        int rows = getSqlMapClientTemplate().update("DELGPR_TGPR_MENU_ROLES.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_MENU_ROLES
     *
     * @ibatorgenerated Tue Sep 25 16:43:19 COT 2012
     */
    public int updateByPrimaryKey(MenuRol record) {
        int rows = getSqlMapClientTemplate().update("DELGPR_TGPR_MENU_ROLES.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}