package bbva.pe.gpr.daoImpl;

import bbva.pe.gpr.bean.Territorio;
import bbva.pe.gpr.dao.TerritorioDAO;

import java.math.BigDecimal;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TerritorioDAOImpl extends SqlMapClientDaoSupport implements TerritorioDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_TERRITORIOS
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public TerritorioDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_TERRITORIOS
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public int deleteByPrimaryKey(BigDecimal codTerritorio) {
        Territorio key = new Territorio();
        key.setCodTerritorio(codTerritorio);
        int rows = getSqlMapClientTemplate().delete("CARDEL_TGPR_TERRITORIOS.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_TERRITORIOS
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void insert(Territorio record) {
        getSqlMapClientTemplate().insert("CARDEL_TGPR_TERRITORIOS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_TERRITORIOS
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public void insertSelective(Territorio record) {
        getSqlMapClientTemplate().insert("CARDEL_TGPR_TERRITORIOS.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_TERRITORIOS
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public Territorio selectByPrimaryKey(BigDecimal codTerritorio) {
        Territorio key = new Territorio();
        key.setCodTerritorio(codTerritorio);
        Territorio record = (Territorio) getSqlMapClientTemplate().queryForObject("CARDEL_TGPR_TERRITORIOS.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_TERRITORIOS
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public int updateByPrimaryKeySelective(Territorio record) {
        int rows = getSqlMapClientTemplate().update("CARDEL_TGPR_TERRITORIOS.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_TERRITORIOS
     *
     * @ibatorgenerated Thu Sep 27 15:02:44 COT 2012
     */
    public int updateByPrimaryKey(Territorio record) {
        int rows = getSqlMapClientTemplate().update("CARDEL_TGPR_TERRITORIOS.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}