package bbva.pe.gpr.daoImpl;


import bbva.pe.gpr.bean.UsuarioRol;
import bbva.pe.gpr.bean.UsuarioRolKey;
import bbva.pe.gpr.dao.UsuarioRolDAO;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UsuarioRolDAOImpl extends SqlMapClientDaoSupport implements UsuarioRolDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_USUARIO_ROLES
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public UsuarioRolDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_USUARIO_ROLES
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public int deleteByPrimaryKey(UsuarioRolKey key) {
        int rows = getSqlMapClientTemplate().delete("CARDEL_TGPR_USUARIO_ROLES.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_USUARIO_ROLES
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public void insert(UsuarioRol record) {
        getSqlMapClientTemplate().insert("CARDEL_TGPR_USUARIO_ROLES.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_USUARIO_ROLES
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public void insertSelective(UsuarioRol record) {
        getSqlMapClientTemplate().insert("CARDEL_TGPR_USUARIO_ROLES.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_USUARIO_ROLES
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public UsuarioRol selectByPrimaryKey(UsuarioRolKey key) {
        UsuarioRol record = (UsuarioRol) getSqlMapClientTemplate().queryForObject("CARDEL_TGPR_USUARIO_ROLES.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_USUARIO_ROLES
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public int updateByPrimaryKeySelective(UsuarioRol record) {
        int rows = getSqlMapClientTemplate().update("CARDEL_TGPR_USUARIO_ROLES.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_USUARIO_ROLES
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    public int updateByPrimaryKey(UsuarioRol record) {
        int rows = getSqlMapClientTemplate().update("CARDEL_TGPR_USUARIO_ROLES.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}