package bbva.pe.gpr.dao;

import bbva.pe.gpr.bean.BancaSub;

public interface BancaSubDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_BANCA_SUB
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    int deleteByPrimaryKey(String codSubbanca);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_BANCA_SUB
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    void insert(BancaSub record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_BANCA_SUB
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    void insertSelective(BancaSub record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_BANCA_SUB
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    BancaSub selectByPrimaryKey(String codSubbanca);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_BANCA_SUB
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    int updateByPrimaryKeySelective(BancaSub record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_BANCA_SUB
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    int updateByPrimaryKey(BancaSub record);
}