package bbva.pe.gpr.dao;

import bbva.pe.gpr.bean.FuncionRol;
import bbva.pe.gpr.bean.FuncionRolKey;

public interface FuncionRolDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_FUNCION_ROLES
     *
     * @ibatorgenerated Tue Sep 25 16:33:28 COT 2012
     */
    int deleteByPrimaryKey(FuncionRolKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_FUNCION_ROLES
     *
     * @ibatorgenerated Tue Sep 25 16:33:28 COT 2012
     */
    void insert(FuncionRol record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_FUNCION_ROLES
     *
     * @ibatorgenerated Tue Sep 25 16:33:28 COT 2012
     */
    void insertSelective(FuncionRol record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_FUNCION_ROLES
     *
     * @ibatorgenerated Tue Sep 25 16:33:28 COT 2012
     */
    FuncionRol selectByPrimaryKey(FuncionRolKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_FUNCION_ROLES
     *
     * @ibatorgenerated Tue Sep 25 16:33:28 COT 2012
     */
    int updateByPrimaryKeySelective(FuncionRol record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_FUNCION_ROLES
     *
     * @ibatorgenerated Tue Sep 25 16:33:28 COT 2012
     */
    int updateByPrimaryKey(FuncionRol record);
}