package bbva.pe.gpr.dao;

import bbva.pe.gpr.bean.MenuRol;
import bbva.pe.gpr.bean.MenuRolKey;

public interface MenuRolDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_MENU_ROLES
     *
     * @ibatorgenerated Tue Sep 25 16:33:28 COT 2012
     */
    int deleteByPrimaryKey(MenuRolKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_MENU_ROLES
     *
     * @ibatorgenerated Tue Sep 25 16:33:28 COT 2012
     */
    void insert(MenuRol record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_MENU_ROLES
     *
     * @ibatorgenerated Tue Sep 25 16:33:28 COT 2012
     */
    void insertSelective(MenuRol record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_MENU_ROLES
     *
     * @ibatorgenerated Tue Sep 25 16:33:28 COT 2012
     */
    MenuRol selectByPrimaryKey(MenuRolKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_MENU_ROLES
     *
     * @ibatorgenerated Tue Sep 25 16:33:28 COT 2012
     */
    int updateByPrimaryKeySelective(MenuRol record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table DELGPR.TGPR_MENU_ROLES
     *
     * @ibatorgenerated Tue Sep 25 16:33:28 COT 2012
     */
    int updateByPrimaryKey(MenuRol record);
}