package bbva.pe.gpr.dao;

import bbva.pe.gpr.bean.UsuarioRol;
import bbva.pe.gpr.bean.UsuarioRolKey;

public interface UsuarioRolDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_USUARIO_ROLES
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    int deleteByPrimaryKey(UsuarioRolKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_USUARIO_ROLES
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    void insert(UsuarioRol record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_USUARIO_ROLES
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    void insertSelective(UsuarioRol record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_USUARIO_ROLES
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    UsuarioRol selectByPrimaryKey(UsuarioRolKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_USUARIO_ROLES
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    int updateByPrimaryKeySelective(UsuarioRol record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_USUARIO_ROLES
     *
     * @ibatorgenerated Tue Oct 09 10:50:13 COT 2012
     */
    int updateByPrimaryKey(UsuarioRol record);
}