package bbva.pe.gpr.service;

import bbva.pe.gpr.bean.Log;

public interface LogService {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_LOGS
     *
     * @ibatorgenerated Mon Sep 24 11:24:02 COT 2012
     */
    void insert(Log record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CARDEL.TGPR_LOGS
     *
     * @ibatorgenerated Mon Sep 24 11:24:02 COT 2012
     */
    void insertSelective(Log record);
}